### ISSUE TITLE
MOSQ_EVT_MESSAGE never called

### ISSUE THREAD

**Issue by sinfitz** [blusewang/mosquitto-delay-message#1]
Hey, @blusewang I'm with mosquitto v2.0.15. for some reason  MOSQ_EVT_MESSAGE never called.
I have tried MOSQ_EVT_DISCONNECT, MOSQ_EVT_BASIC_AUTH and MOSQ_EVT_TICK. after registered, all worked as expect.
Do you have any idea why? wondering if there are any special settings for plugin receiving event in mosquitto.conf? I can't find docs for this. Appreciate very much in advance.

**Comment by blusewang** [comment]
In my case, there is no special settings for plugin receiving event in `mosquitto.conf` file.
I use `mosquitto v2.0.15` too, and register `MOSQ_EVT_MESSAGE` in `mosquitto_plugin_init`.
Plugin code refers to https://github.com/eclipse/mosquitto/tree/master/plugins
Suggest you print register response.like this:
```
    int rs = mosquitto_callback_register(mos_pid, MOSQ_EVT_MESSAGE, handle_delay_message, NULL, NULL);
    if (rs != MOSQ_ERR_SUCCESS) {
        mosquitto_log_printf(MOSQ_LOG_ERR, "mosquitto_callback_register MOSQ_EVT_MESSAGE err:%d", rs);
        return rs;
    }
```

**Comment by sinfitz** [comment]
My bad, acl typo ;) Thank you for the reply
